version: '3.3'

services:

  app:
    image: funklid/scan-redcap
    build: .
    container_name: scan-redcap
    env_file:
      - .env
        # ports:
            #  - "4321:80"
    expose:
      - "80"
    volumes:
      - .:/var/www/html

  #phpmyadmin:
  #  image: phpmyadmin/phpmyadmin:4.7
  #  # volumes:
  #  #   - ./docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
  #  env_file:
  #    - .env
  #  #ports:
  #  #  - "5432:80"
  #  depends_on:
  #    - mysql

networks:
  default:
    external:
      name: webproxy
# https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion

